Added the Dockerfile and updated the build configuration.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,32 +1,87 @@
-# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-name: CoinBase Backend CI.
+name: test-build
 
 on:
   push:
-    branches: [ "master" ]
+    branches: [ master ]
   pull_request:
-    branches: [ "master" ]
+    branches: [ master ]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 21
-      uses: actions/setup-java@v4
-      with:
-        java-version: '21'
-        distribution: 'temurin'
-        cache: maven
-    - name: Build with Maven.
-      run: mvn -B package --file pom.xml
+    steps: # Step 1: Checkout the latest code from the repository
+      - uses: actions/checkout@v4
 
+      # Step 2: Set up JDK 21 for the build process
+      - name: Setting up JDK 21.
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+          cache: maven
+
+      # Step 3: Build the project using Maven
+      - name: Build with Maven.
+        run: mvn clean install
+
+      # Step 4: Setup AWS ECR Details
+      - name: Setting up AWS ECR Details.
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      # Step 5: Login to Amazon ECR
+      - name: Login to Amazon ECR.
+        id: login-pf-aws-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      # Step 6: Build and push Docker image
+      - name: Build and push Docker image.
+        env:
+          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+          IMAGE_TAG: 'latest'
+        run: |
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:coinbase-$IMAGE_TAG .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:coinbase-$IMAGE_TAG
+
+      # Step 7: Deploy Docker image to EC2
+      - name: Deploying to EC2.
+        env:
+          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
+          HOST: ${{ secrets.EC2_HOST }}
+          USER: ${{ secrets.EC2_USER }}
+          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          # Save the private key to a file
+          echo "$PRIVATE_KEY" > private_key.pem
+          chmod 600 private_key.pem
+
+          # SSH into EC2 and deploy the Docker container.
+          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
+            # Print variables for debugging
+            echo "ECR_REGISTRY: $ECR_REGISTRY"
+            echo "ECR_REPOSITORY: $ECR_REPOSITORY"
+            echo "IMAGE_TAG: $IMAGE_TAG"
+
+            # Stop and remove all running containers
+            docker stop \$(docker ps -q) || true
+            docker rm \$(docker ps -a -q) || true
+
+            # Login to ECR
+            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
+
+            # Pull the new image from ECR
+            docker pull "$ECR_REGISTRY/$ECR_REPOSITORY:coinbase-$IMAGE_TAG"
+
+            # Run the new container
+            docker run -d --name coinbase -p 80:8080 "$ECR_REGISTRY/$ECR_REPOSITORY:coinbase-$IMAGE_TAG"
+          EOF
+
+          # Clean up the private key file
+          rm private_key.pem
